destination: ../www/fbtft.org
exclude: ['*.rb', 'build']
relative_permalinks: false
markdown: kramdown

image:
  presets:
    displays:
      width: 300

github:
  commits:
    - url: 'https://api.github.com/repos/notro/fbtft/commits'
      category: newsdriver
    - url: 'https://api.github.com/repos/notro/rpi-firmware/commits'
      category: newskernel
